return {
    name        = "Solar Colour",
    author      = "pxlflux",
    version     = "1.0.0",
    description = "Modern, rounded icons based on the Solar icon set by 480 Design",

    map = {
        -- System icons
        sui_menu                    = "menu.svg",
        sui_search                  = "search.svg",
        sui_back                    = "chevron_left.svg",
        sui_browse_normal           = "folder.svg",
        sui_browse_author           = "authors.svg",
        sui_browse_series           = "series.svg",
        sui_browse_tags             = "tags.svg",
        sui_pager_prev              = "chevron_left.svg",
        sui_pager_next              = "chevron_right.svg",
        sui_pager_first             = "pager_first.svg",
        sui_pager_last              = "pager_last.svg",
        sui_navpager_prev           = "chevron_left.svg",
        sui_navpager_next           = "chevron_right.svg",
        sui_coll_back               = "coll_back.svg",
        sui_qa_folder               = "folder.svg",
        sui_qa_plugin               = "qa_plugin.svg",
        sui_qa_system               = "settings.svg",
        sui_qa_group                = "qa_group.svg",
        sui_fc_empty                = "folder.svg",
        sui_tab_main                = "menu.svg",
        sui_tab_setting             = "settings.svg",
        sui_tab_tools               = "tab_tools.svg",
        sui_tab_search              = "search.svg",
        sui_tab_fm_settings         = "tab_fm_settings.svg",
        sui_tab_navigation          = "tab_navigation.svg",
        sui_tab_typeset             = "tab_typeset.svg",
        sui_tab_filebrowser         = "tab_filebrowser.svg",
        sui_tab_qs_panel            = "tab_qs_panel.svg",
        -- Actions
        sui_action_library          = "library.svg",
        sui_action_homescreen       = "homescreen.svg",
        sui_action_collections      = "collections.svg",
        sui_action_history          = "history.svg",
        sui_action_continue         = "continue.svg",
        sui_action_favorites        = "favorites.svg",
        sui_action_bookmark_browser = "bookmark_browser.svg",
        sui_action_wifi_toggle      = "wifi_toggle.svg",
        sui_action_frontlight       = "frontlight.svg",
        sui_action_night_mode       = "night_mode.svg",
        sui_action_stats_calendar   = "stats_calendar.svg",
        sui_action_power            = "power.svg",
        sui_action_browse_authors   = "authors.svg",
        sui_action_browse_series    = "series.svg",
        sui_action_browse_tags      = "tags.svg",
        sui_action_settings         = "settings.svg",
        sui_action_recent           = "recent.svg",
        sui_action_random_document  = "random_document.svg",
    },
}
